quotes = {'"Winter is coming."': '-Ned Stark',
          '"You know nothing Jon Snow."': '-Ygritte',
          '"Fear cuts deeper than swords."': '-Arya Stark',
          '"Some wounds never truly heal, and bleed again at the slightest word."': '-Ned Stark',
          '"A lion doesn’t concern himself with the opinions of a sheep."': '-Tywin Lannister',
          '"If you think this has a happy ending you haven’t been paying attention."': '-Ramsey Bolton',
          '"A man with no motive is a man no one suspects. Always keep your foes confused."': '-Lord Baelish',
          '“Any man who must say ‘I am the king’ is no true king.”': '-Tywin Lannister',
          '“A ruler who kills those devoted to her is not a ruler who inspires devotion.”': '-Tyrion Lannister',
          '“Power resides where men believe it resides. It’s a trick, a shadow on the wall. And a very small man can cast a very large shadow.”': '-Lord Varys',
          '“When you play the game of thrones, you win or you die.”': '-Cersei Lannister',
          '“Never forget what you are. The rest of the world will not. Wear it like armour, and it can never be used to hurt you.”': '-Tyrion Lannister',
          '“Chaos isn’t a pit. Chaos is a ladder.”': '-Lord Baelish',
          '“The world is overflowing with horrible things, but they’re all a tray of cakes next to death.”': '-Olenna Tyrell',
          '“The night is dark and full of terrors.”': '-Melisandre',
          '“There is only one god and his name is Death, and there is only one thing we say to Death: ‘Not today.’”': '-Syrio Forel',
          '“The freedom to make my own mistakes was all I ever wanted.”': '-Mance Rayder',
          '“A girl is Arya Stark of Winterfell and I’m going home.”': '-Arya Stark',
          '“Tell them the North remembers. Tell them winter came for House Frey.”': '-Arya Stark',
          '“Not today.”': '-Arya Stark',
          '“Leave one wolf alive and the sheep are never safe.”': '-Arya Stark',
          '“I thought if I could make something so good, so pure, maybe I’m not a monster.”': '-Cersei Lannister',
          '“Power is power.”': '-Cersei Lannister',
          '“I am not your little princess. I am Daenerys Stormborn of the blood of old Valyria and I will take what is mine — with fire and blood, I will take it.”': '-Daenerys Targaryen',
          '“I’m not going to stop the wheel, I’m going to break the wheel.”': '-Daenerys Targaryen',
          '“Dracarys.”': '-Daenerys Targaryen',
          '“Let the priests argue over good and evil, slavery is real. I can end it, I will end it, and I will end those behind it.”': '-Daenerys Targaryen',
          '“I am a Khaleesi of the Dothraki. I am the wife of the great Kahl and I carry his son inside me. The next time you raise a hand to me will be the last time you have hands.”': '-Daenerys Targaryen',
          '“A dragon is not a slave.”': '-Daenerys Targaryen',
          '“When enough people make false promises words stop meaning anything. Then there are no more answers, only better and better lies.”': '-Jon Snow',
          '“My watch has ended.”': '-Jon Snow',
          '“A mind needs books like a sword needs a whetstone.”': '-Tyrion Lannister',
          '“It’s hard to put a leash on a dog once you’ve put a crown on its head.”': '-Tyrion Lannister',
          '“Hold the door!”': '-Meera Reed',
          '“Can a man be brave if he’s afraid?”, “That’s the only time he can be brave,”': '— Bran and Ned Stark',
          '“The man who passes the sentence should swing the sword.”': '-Ned Stark'}
